CREATE TABLE public.court_block_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id bigint NOT NULL REFERENCES public.venues(id) ON DELETE CASCADE,
  court_id bigint NOT NULL REFERENCES public.courts(id) ON DELETE CASCADE,
  blocked_court_id bigint NOT NULL REFERENCES public.courts(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT court_block_rules_distinct CHECK (court_id <> blocked_court_id),
  CONSTRAINT court_block_rules_unique UNIQUE (court_id, blocked_court_id)
);

GRANT SELECT ON public.court_block_rules TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.court_block_rules TO authenticated;
GRANT ALL ON public.court_block_rules TO service_role;

ALTER TABLE public.court_block_rules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view court block rules"
  ON public.court_block_rules FOR SELECT USING (true);

CREATE POLICY "Staff can insert court block rules"
  ON public.court_block_rules FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.staff s WHERE s.user_id = auth.uid() AND s.venue_id = court_block_rules.venue_id));

CREATE POLICY "Staff can update court block rules"
  ON public.court_block_rules FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.staff s WHERE s.user_id = auth.uid() AND s.venue_id = court_block_rules.venue_id))
  WITH CHECK (EXISTS (SELECT 1 FROM public.staff s WHERE s.user_id = auth.uid() AND s.venue_id = court_block_rules.venue_id));

CREATE POLICY "Staff can delete court block rules"
  ON public.court_block_rules FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.staff s WHERE s.user_id = auth.uid() AND s.venue_id = court_block_rules.venue_id));

CREATE INDEX court_block_rules_blocked_idx ON public.court_block_rules (blocked_court_id);
CREATE INDEX court_block_rules_venue_idx ON public.court_block_rules (venue_id);

-- Seed rules from existing shared surfaces (courts on the same slab, different sports block each other)
INSERT INTO public.court_block_rules (venue_id, court_id, blocked_court_id)
SELECT a.venue_id, a.id, b.id
  FROM public.courts a
  JOIN public.courts b
    ON b.physical_court_id = a.physical_court_id
   AND b.id <> a.id
   AND b.sport_id <> a.sport_id
ON CONFLICT DO NOTHING;

-- Booking validation now honours explicit pairwise blocking rules
CREATE OR REPLACE FUNCTION public.validate_booking()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $function$
DECLARE _pc_id BIGINT; _sport_id BIGINT; _capacity INT; _same INT; _other INT; _t timestamptz;
BEGIN
  IF NEW.status <> 'confirmed' THEN RETURN NEW; END IF;
  SELECT physical_court_id, sport_id, capacity INTO _pc_id, _sport_id, _capacity
    FROM public.courts WHERE id = NEW.court_id;
  IF _pc_id IS NULL THEN RAISE EXCEPTION 'Court not found'; END IF;

  _t := NEW.start_time;
  WHILE _t < NEW.end_time LOOP
    IF NOT public.court_is_open(NEW.court_id, _t) THEN
      RAISE EXCEPTION 'That time is outside this court''s operating hours.' USING ERRCODE = '23514';
    END IF;
    _t := _t + interval '1 hour';
  END LOOP;

  SELECT COUNT(*) INTO _other
    FROM public.bookings b
    JOIN public.court_block_rules r
      ON r.court_id = b.court_id AND r.blocked_court_id = NEW.court_id
   WHERE b.status = 'confirmed'
     AND (TG_OP = 'INSERT' OR b.id <> NEW.id)
     AND b.start_time < NEW.end_time AND b.end_time > NEW.start_time;
  IF _other > 0 THEN
    RAISE EXCEPTION 'Another court sharing this space is already booked at that time.' USING ERRCODE = '23P01';
  END IF;

  SELECT COUNT(*) INTO _same
    FROM public.bookings b
   WHERE b.status = 'confirmed'
     AND (TG_OP = 'INSERT' OR b.id <> NEW.id)
     AND b.court_id = NEW.court_id
     AND b.start_time < NEW.end_time AND b.end_time > NEW.start_time;
  IF _same >= _capacity THEN
    RAISE EXCEPTION 'All % slots for this court at that time are already booked.', _capacity USING ERRCODE = '23P01';
  END IF;

  RETURN NEW;
END; $function$;

CREATE OR REPLACE FUNCTION public.get_court_availability(_court_id bigint, _from timestamp with time zone, _to timestamp with time zone)
RETURNS TABLE(hour_start timestamp with time zone, remaining integer, blocked_by_other_sport boolean)
LANGUAGE plpgsql
STABLE
SET search_path TO 'public'
AS $function$
DECLARE _capacity INT;
BEGIN
  SELECT capacity INTO _capacity FROM public.courts WHERE id = _court_id;
  IF _capacity IS NULL THEN RETURN; END IF;

  RETURN QUERY
  WITH hours AS (
    SELECT gs AS hour_start
      FROM generate_series(date_trunc('hour', _from), _to - interval '1 hour', interval '1 hour') AS gs
  ),
  same_court AS (
    SELECT h.hour_start, COUNT(*)::INT AS n
      FROM hours h
      JOIN public.bookings b ON b.status = 'confirmed' AND b.court_id = _court_id
     WHERE b.start_time < h.hour_start + interval '1 hour' AND b.end_time > h.hour_start
     GROUP BY h.hour_start
  ),
  blocked AS (
    SELECT h.hour_start, COUNT(*)::INT AS n
      FROM hours h
      JOIN public.bookings b ON b.status = 'confirmed'
      JOIN public.court_block_rules r
        ON r.court_id = b.court_id AND r.blocked_court_id = _court_id
     WHERE b.start_time < h.hour_start + interval '1 hour' AND b.end_time > h.hour_start
     GROUP BY h.hour_start
  )
  SELECT h.hour_start,
         CASE WHEN COALESCE(o.n, 0) > 0 THEN 0
              ELSE GREATEST(_capacity - COALESCE(s.n, 0), 0) END,
         COALESCE(o.n, 0) > 0
    FROM hours h
    LEFT JOIN same_court s USING (hour_start)
    LEFT JOIN blocked o USING (hour_start)
    ORDER BY h.hour_start;
END; $function$;