
CREATE TABLE public.physical_courts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id BIGINT NOT NULL REFERENCES public.venues(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  map_emoji TEXT,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ON public.physical_courts (venue_id);

GRANT SELECT ON public.physical_courts TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.physical_courts TO authenticated;
GRANT ALL ON public.physical_courts TO service_role;

ALTER TABLE public.physical_courts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view physical courts"
  ON public.physical_courts FOR SELECT USING (true);
CREATE POLICY "Staff can insert physical courts"
  ON public.physical_courts FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.staff s WHERE s.user_id = auth.uid() AND s.venue_id = physical_courts.venue_id));
CREATE POLICY "Staff can update physical courts"
  ON public.physical_courts FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.staff s WHERE s.user_id = auth.uid() AND s.venue_id = physical_courts.venue_id))
  WITH CHECK (EXISTS (SELECT 1 FROM public.staff s WHERE s.user_id = auth.uid() AND s.venue_id = physical_courts.venue_id));
CREATE POLICY "Staff can delete physical courts"
  ON public.physical_courts FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.staff s WHERE s.user_id = auth.uid() AND s.venue_id = physical_courts.venue_id));

CREATE TRIGGER set_physical_courts_updated_at
  BEFORE UPDATE ON public.physical_courts
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.courts
  ADD COLUMN physical_court_id BIGINT REFERENCES public.physical_courts(id) ON DELETE RESTRICT,
  ADD COLUMN capacity INT NOT NULL DEFAULT 1,
  ADD COLUMN footprint NUMERIC(5,4) NOT NULL DEFAULT 1.0;

-- Backfill 1:1 using a per-row loop so each court gets its own physical_court
DO $$
DECLARE r RECORD; new_pc_id BIGINT;
BEGIN
  FOR r IN SELECT id, venue_id, name, map_emoji FROM public.courts ORDER BY id LOOP
    INSERT INTO public.physical_courts (venue_id, name, map_emoji)
      VALUES (r.venue_id, r.name, r.map_emoji)
      RETURNING id INTO new_pc_id;
    UPDATE public.courts SET physical_court_id = new_pc_id WHERE id = r.id;
  END LOOP;
END $$;

ALTER TABLE public.courts ALTER COLUMN physical_court_id SET NOT NULL;
CREATE INDEX ON public.courts (physical_court_id);

CREATE OR REPLACE FUNCTION public.get_court_availability(
  _court_id BIGINT, _from TIMESTAMPTZ, _to TIMESTAMPTZ
)
RETURNS TABLE(hour_start TIMESTAMPTZ, remaining INT, blocked_by_other_sport BOOLEAN)
LANGUAGE plpgsql STABLE SET search_path = public AS $$
DECLARE _pc_id BIGINT; _sport_id BIGINT; _capacity INT;
BEGIN
  SELECT physical_court_id, sport_id, capacity INTO _pc_id, _sport_id, _capacity
    FROM public.courts WHERE id = _court_id;
  IF _pc_id IS NULL THEN RETURN; END IF;

  RETURN QUERY
  WITH hours AS (
    SELECT gs AS hour_start
      FROM generate_series(date_trunc('hour', _from), _to - interval '1 hour', interval '1 hour') AS gs
  ),
  same_sport AS (
    SELECT h.hour_start, COUNT(*)::INT AS n
      FROM hours h
      JOIN public.bookings b ON b.status = 'confirmed'
      JOIN public.courts sib ON sib.id = b.court_id
     WHERE sib.physical_court_id = _pc_id AND sib.sport_id = _sport_id
       AND b.start_time < h.hour_start + interval '1 hour' AND b.end_time > h.hour_start
     GROUP BY h.hour_start
  ),
  other_sport AS (
    SELECT h.hour_start, COUNT(*)::INT AS n
      FROM hours h
      JOIN public.bookings b ON b.status = 'confirmed'
      JOIN public.courts sib ON sib.id = b.court_id
     WHERE sib.physical_court_id = _pc_id AND sib.sport_id <> _sport_id
       AND b.start_time < h.hour_start + interval '1 hour' AND b.end_time > h.hour_start
     GROUP BY h.hour_start
  )
  SELECT h.hour_start,
         CASE WHEN COALESCE(o.n, 0) > 0 THEN 0
              ELSE GREATEST(_capacity - COALESCE(s.n, 0), 0) END,
         COALESCE(o.n, 0) > 0
    FROM hours h
    LEFT JOIN same_sport s USING (hour_start)
    LEFT JOIN other_sport o USING (hour_start)
    ORDER BY h.hour_start;
END; $$;

GRANT EXECUTE ON FUNCTION public.get_court_availability(BIGINT, TIMESTAMPTZ, TIMESTAMPTZ) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.validate_booking()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
DECLARE _pc_id BIGINT; _sport_id BIGINT; _capacity INT; _same INT; _other INT;
BEGIN
  IF NEW.status <> 'confirmed' THEN RETURN NEW; END IF;
  SELECT physical_court_id, sport_id, capacity INTO _pc_id, _sport_id, _capacity
    FROM public.courts WHERE id = NEW.court_id;
  IF _pc_id IS NULL THEN RAISE EXCEPTION 'Court not found'; END IF;

  SELECT COUNT(*) INTO _other
    FROM public.bookings b JOIN public.courts c ON c.id = b.court_id
   WHERE b.status = 'confirmed'
     AND (TG_OP = 'INSERT' OR b.id <> NEW.id)
     AND c.physical_court_id = _pc_id AND c.sport_id <> _sport_id
     AND b.start_time < NEW.end_time AND b.end_time > NEW.start_time;
  IF _other > 0 THEN
    RAISE EXCEPTION 'This surface is already booked for a different sport at that time.' USING ERRCODE = '23P01';
  END IF;

  SELECT COUNT(*) INTO _same
    FROM public.bookings b JOIN public.courts c ON c.id = b.court_id
   WHERE b.status = 'confirmed'
     AND (TG_OP = 'INSERT' OR b.id <> NEW.id)
     AND c.physical_court_id = _pc_id AND c.sport_id = _sport_id
     AND b.start_time < NEW.end_time AND b.end_time > NEW.start_time;
  IF _same >= _capacity THEN
    RAISE EXCEPTION 'All % slots for this sport at that time are already booked.', _capacity USING ERRCODE = '23P01';
  END IF;

  RETURN NEW;
END; $$;

CREATE TRIGGER validate_booking_trg
  BEFORE INSERT OR UPDATE ON public.bookings
  FOR EACH ROW EXECUTE FUNCTION public.validate_booking();
